server:
  port: 9007

spring:
  application:
    name: notification-service
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27017/campusnotify}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}

management:
  endpoints:
    web:
      exposure:
        include: "*"

